### PR TITLE
Broke presentations out into re-usable files and added a slide about PIXLS.US.

### PR DESCRIPTION
**Pull request by paperdigits**
Added a pandoc template for reveal.js, since the version included with Fedora 23 has an error in it.

Added my finished presentation.

Move all finished presentations into their own folder.

Updated instructions in README.md to include using pandoc to generate the slides.

### CODE REVIEW

**Comment by patdavid** [comment]
Awesome, thank you for this!  I must have missed the notification that there was a PR waiting for me. :(

**Comment by patdavid** [comment]
Ack!  That's what I get for not pulling and testing locally first. :)  My changes got exploded.  Reverting, and moving to sort this out.

**Comment by patdavid** [comment]
@paperdigits - did you pull before issuing the PR to check it?  You seem to have left off some of the existing presentation folders?

I've been trying to keep each set of presentations in their own sub-folders to keep things organized.

**Comment by paperdigits** [comment]
I thought I was up-to-date, but maybe not! I'll pull soon and check it out! Sorry!

**Pull request merged**
